name: "Produce Presentation Content"

on: "push"

jobs:
  move_it:
    name: "Build PowerPoint Presentation"
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: "Upload Presentation Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist/

  release-content:
    name: "Create GitHub Release"
    runs-on: windows-latest
    needs: [move_it]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Download Presentation Artifacts"
        uses: actions/download-artifact@v3
        with:
          name: dist-folder
          path: dist/

      - name: "Create GitHub Release"
        uses: phuonghuynh/action-ghrelease@v1.1.0
        with:
          files: ${{env.TARBALL}}
          tag_name: v${{ github.run_number }}
          name: Release V${{ github.run_number }}
